apiVersion: v1 
kind: Pod  
metadata: 
 name: bear  
spec:
 containers: 
 - name: bear 
   image: yanivomc/spring-music
   ports: 
   - containerPort: 8080
 - name: nginx 
   image: nginx:1.7.9 
   ports: 
   - containerPort: 80