apiVersion: v1
kind: Pod
metadata:
  name: volume_exc
spec:
  containers:
  - image: supergiantkir/animals:bear
    name: app1
    volumeMounts:
    - mountPath: /storage
      name: app-storage
  containers:
  - image: yanivomc/spring-music:latest
    name: app2
    volumeMounts:
    - mountPath: /storage
      name: app-storage      
  volumes:
  - name: app-storage
    hostPath:
      path: /tmp/files
      type: DirectoryOrCreate