apiVersion: v1
kind: Pod 
metadata: 
 name: volumes
spec:
 containers: 
 - name: app1
   volumeMounts:
   - name: app-storage
     mountPath: /storage
   image: yanivomc/spring-music:latest 
   ports: 
 - name: app2
   volumeMounts:
  - name: app-storage
    mountPath: /storage
   image: supergiantkir/animals:bear
  
volumes:
 - name: app-storage
   hostPath:
    path: /tmp/files