apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment-test
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 2
  strategy:
        type: RollingUpdate
        rollingUpdate:
          maxSurge: 5
          maxUnavilable: 0
  template: 
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80