apiVersion: apps/v1
kind: Deployment
metadata:
  name: animals-moose
spec:
  selector:
    matchLabels:
      app: moose
  replicas: 2
  template: 
    metadata:
      labels:
        app: moose
    spec:
      containers:
      - name: moose
        image: supergiantkir/animals:moose
        ports:
        - containerPort: 80

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: animals-bear
spec:
  selector:
    matchLabels:
      app: bear
  replicas: 2
  template: 
    metadata:
      labels:
        app: bear
    spec:
      containers:
      - name: bear
        image: supergiantkir/animals:bear
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: moose-service
spec:
  selector:
    app: moose
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: bear-service
spec:
  selector:
    app: bear
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 80    