kind: Service     
apiVersion: v1     
metadata:
  name: {{ .Values.service_name }}
spec:
  selector:
    app: music    
  type: {{ .Values.service_type | default "NodePort" }}
  ports:         
  - name: http   
    protocol: TCP
    port:  {{ .Values.port }}
    targetPort: {{ .Values.targetport }}