apiVersion: apps/v1
kind: Deployment
metadata:
  name:  {{ .Release.Name }}-{{ .Chart.name }}-{{ .Chart.version }}
  labels:
  {{- include "spring.labels" . | nindent 3}}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
    {{- include "spring.labels" . | nindent 4}}
  template:
    metadata:
      labels:
      {{- include "spring.labels" . | nindent 5}}
    spec:
      containers:
        - name: {{ .Values.name }}
          image: {{ .Values.image.name }}:{{ .Values.image.tag }}
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
