apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service_name }}
  labels:
spec:
 ### ADD IF ENV=LOCAL > TYPE:NODEPORT ELSE > 
  type: {{ .Values.service_type | default "NodePort" }}
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8080
  selector:
